### PR TITLE
project fails to render due typo in project variable

### PR DESCRIPTION
**Pull request by betolink**
I tried to use the current project and got a "'collections.OrderedDict object' has no attribute 'project_name'". The variable has now the proper name.

### CODE REVIEW

**Comment by betolink** [comment]
Also, the README says we need a personal github token, is this still required? the name is not valid according to Github and is not used in the project, there is a TOOLS_BOT_PAK in the release action. Is this the updated secret name?

**Comment by jhkennedy** [comment]
> I tried to use the current project and got a "'collections.OrderedDict object' has no attribute 'project_name'". The variable has now the proper name.

Woops, this is a regression I introduced in #88 apparently. Thanks!

**Review by jhkennedy — APPROVED** [review]
I'll circle around in another PR for the token name.
